# Generated by Django 5.2.9 on 2025-12-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaKontraktow',
            fields=[
                ('id_logu', models.AutoField(primary_key=True, serialize=False)),
                ('id_zawodnika', models.BigIntegerField(blank=True, null=True)),
                ('stara_kwota', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('nowa_kwota', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('data_zmiany', models.DateTimeField(blank=True, null=True)),
                ('uzytkownik_zmieniajacy', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Log: Zmiana Kontraktu',
                'verbose_name_plural': 'Logi: Zmiany Kontraktów',
                'db_table': 'historia_kontraktow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kontrakty',
            fields=[
                ('id_kontraktu', models.AutoField(primary_key=True, serialize=False)),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=15)),
                ('typ_kontraktu', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Kontrakt',
                'verbose_name_plural': 'Kontrakty',
                'db_table': 'kontrakty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kontuzje',
            fields=[
                ('id_kontuzji', models.AutoField(primary_key=True, serialize=False)),
                ('data_zgloszenia', models.DateField(blank=True, null=True)),
                ('opis_kontuzji', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('przewidywany_powrot', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kontuzja',
                'verbose_name_plural': 'Kontuzje',
                'db_table': 'kontuzje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogiBledowMecze',
            fields=[
                ('id_logu', models.AutoField(primary_key=True, serialize=False)),
                ('opis_bledu', models.TextField(blank=True, null=True)),
                ('data_zdarzenia', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log: Błąd Meczu',
                'verbose_name_plural': 'Logi: Błędy Meczów',
                'db_table': 'logi_bledow_mecze',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mecze',
            fields=[
                ('id_meczu', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('data_meczu', models.DateField()),
                ('wynik_gospodarz', models.IntegerField(blank=True, null=True)),
                ('wynik_gosc', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mecz',
                'verbose_name_plural': 'Mecze',
                'db_table': 'mecze',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RankingiZespolow',
            fields=[
                ('kod_sezonu', models.CharField(max_length=20)),
                ('zespol', models.CharField(db_column='zespol', max_length=100, primary_key=True, serialize=False)),
                ('konferencja', models.CharField(max_length=20)),
                ('wygrane', models.IntegerField()),
                ('przegrane', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tabela Ligowa',
                'verbose_name_plural': 'Tabela Ligowa',
                'db_table': 'widok_tabela_ligowa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RaportDomWyjazd',
            fields=[
                ('nazwa', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mecze_dom', models.IntegerField()),
                ('wygrane_dom', models.IntegerField()),
                ('mecze_wyjazd', models.IntegerField()),
                ('wygrane_wyjazd', models.IntegerField()),
                ('procent_wygranych_dom', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Raport: Twierdza',
                'verbose_name_plural': 'Raporty: Twierdza',
                'db_table': 'raport_dom_wyjazd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RaportEfektywnoscFinansowa',
            fields=[
                ('id_zawodnika', models.BigIntegerField(db_column='id_zawodnika', primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('zespol', models.CharField(max_length=100)),
                ('kontrakt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('koszt_jednego_punktu', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name': 'Raport: Moneyball',
                'verbose_name_plural': 'Raporty: Moneyball',
                'db_table': 'raport_efektywnosc_finansowa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RaportKosztKontuzji',
            fields=[
                ('nazwa', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('liczba_kontuzjowanych', models.IntegerField()),
                ('zamrozone_pieniadze', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name': 'Raport: Szpital',
                'verbose_name_plural': 'Raporty: Szpital',
                'db_table': 'raport_koszt_kontuzji',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sezony',
            fields=[
                ('id_sezonu', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID Sezonu')),
                ('rok_poczatkowy', models.IntegerField(blank=True, null=True)),
                ('opis', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Sezon',
                'verbose_name_plural': 'Sezony',
                'db_table': 'sezony',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatystykiZawodnikow',
            fields=[
                ('id_statystyki', models.AutoField(primary_key=True, serialize=False)),
                ('punkty', models.IntegerField(default=0)),
                ('asysty', models.IntegerField(default=0)),
                ('zbiorki', models.IntegerField(default=0)),
                ('przechwyty', models.IntegerField(default=0)),
                ('bloki', models.IntegerField(default=0)),
                ('straty', models.IntegerField(default=0)),
                ('minuty', models.CharField(blank=True, max_length=10, null=True)),
                ('plus_minus', models.IntegerField(blank=True, null=True)),
                ('skutecznosc_z_gry', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Statystyka',
                'verbose_name_plural': 'Statystyki',
                'db_table': 'statystyki_zawodnikow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trenerzy',
            fields=[
                ('id_trenera', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('czy_glowny', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trener',
                'verbose_name_plural': 'Trenerzy',
                'db_table': 'trenerzy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zawodnicy',
            fields=[
                ('id_zawodnika', models.BigIntegerField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('czy_aktywny', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('kraj_pochodzenia', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Zawodnik',
                'verbose_name_plural': 'Zawodnicy',
                'db_table': 'zawodnicy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zespoly',
            fields=[
                ('id_zespolu', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=100)),
                ('miasto', models.CharField(max_length=100)),
                ('skrot', models.CharField(max_length=10)),
                ('konferencja', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Zespół',
                'verbose_name_plural': 'Zespoły',
                'db_table': 'zespoly',
                'managed': False,
            },
        ),
    ]
