# Generated by Django 5.2.9 on 2025-12-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankingizespolow',
            options={'managed': False, 'ordering': ['-procent_zwyciestw', '-wygrane'], 'verbose_name': 'Tabela Ligowa'},
        ),
    ]
