# Generated by Django 6.0 on 2026-01-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_app', '0002_alter_rankingizespolow_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZatrudnienieTrenerow',
            fields=[
                ('id_zatrudnienia', models.AutoField(primary_key=True, serialize=False)),
                ('czy_glowny', models.BooleanField(default=True, verbose_name='Trener główny')),
            ],
            options={
                'verbose_name': 'Zatrudnienie trenera',
                'verbose_name_plural': 'Zatrudnienia trenerów',
                'db_table': 'zatrudnienie_trenerow',
                'managed': False,
            },
        ),
    ]
